// ============ Jev router audit — phrasing corpus ============
// Realistic phrasings for a YatraFlow group trip planner, grouped by the intent
// the app has a handler for.
//
// `want` is what a human would expect the router to pick. It is NOT ground truth
// and it is NOT used to score anything — agreement is measured between the code's
// actual route and Jev's independent judgment. `want` is reported alongside so a
// disagreement can be triaged at a glance: when code, Jev and `want` all differ,
// the likely culprit is this file's expectation (or the taxonomy), not the router.
//
// Prefixes: qp = quickPrompts verbatim · t/a/c/k/r/f/d/p/s/y/u/m = intent probes
//           n = out of the assistant's scope (should abstain)
//           x = traps: false-positive keywords and genuinely ambiguous asks

export interface Phrasing {
  id: string
  text: string
  want: string
}

export const CORPUS: Phrasing[] = [
  // ---- qp: the app's own quickPrompts, verbatim (the control group) ----
  { id: 'qp1', text: 'Make Day 2 less tiring', want: 'tiring' },
  { id: 'qp2', text: 'Can we reach the airport by 5 PM if we add this stop?', want: 'airport' },
  { id: 'qp3', text: 'Suggest a cheaper alternative', want: 'cheaper' },
  { id: 'qp4', text: 'Give us three options if it rains', want: 'rain' },
  { id: 'qp5', text: 'Create a family-friendly version', want: 'family' },
  { id: 'qp6', text: 'What should we remove if we are travelling with children?', want: 'kids' },
  { id: 'qp7', text: 'Compare a relaxed itinerary with a packed itinerary', want: 'compare' },
  { id: 'qp8', text: 'Identify the biggest risks in this plan', want: 'risks' },
  { id: 'qp9', text: 'Create a backup plan for a transport delay', want: 'delay' },
  { id: 'qp10', text: 'Turn this itinerary into a YouTube description', want: 'youtube' },

  // ---- t: make a day less demanding (handler: makeLessTiring) ----
  { id: 't01', text: 'Day 2 looks brutal, can we ease off?', want: 'tiring' },
  { id: 't02', text: 'My parents are coming, is this too much walking?', want: 'tiring' },
  { id: 't03', text: 'Can we slow the whole thing down a bit?', want: 'tiring' },
  { id: 't04', text: 'Day 3 has too many stops', want: 'tiring' },
  { id: 't05', text: 'This day is exhausting', want: 'tiring' },
  { id: 't06', text: 'We will be dead by evening on day 1', want: 'tiring' },
  { id: 't07', text: 'Can we take it easy on the second day?', want: 'tiring' },
  { id: 't08', text: 'Reduce the driving on day 4', want: 'tiring' },
  { id: 't09', text: 'Too much back and forth, simplify day 2', want: 'tiring' },
  { id: 't10', text: 'Day 1 is too rushed', want: 'tiring' },
  { id: 't11', text: 'Lighten the load on the last day', want: 'tiring' },
  { id: 't12', text: 'We have elders with us, day 2 needs to be gentler', want: 'tiring' },
  { id: 't13', text: 'Trim day 2 a little', want: 'tiring' },
  { id: 't14', text: 'Day 2 feels overstuffed', want: 'tiring' },
  { id: 't15', text: 'Fewer stops on day 3 please', want: 'tiring' },
  { id: 't16', text: 'Cut down the travel time on day 2', want: 'tiring' },

  // ---- a: reach a fixed flight or train departure (handler: airportFeasibility) ----
  { id: 'a01', text: 'We need to catch a 6am flight on the last day', want: 'airport' },
  { id: 'a02', text: 'Will we make our train if we leave at 9?', want: 'airport' },
  { id: 'a03', text: 'Our flight is at 5pm and we want to visit the tea museum first', want: 'airport' },
  { id: 'a04', text: 'Do we have enough time before the flight?', want: 'airport' },
  { id: 'a05', text: 'Can we fit the museum in before our departure?', want: 'airport' },
  { id: 'a06', text: 'We have a train to catch at 4', want: 'airport' },
  { id: 'a07', text: 'Is there buffer before the airport drop?', want: 'airport' },
  { id: 'a08', text: 'We booked a 7am flight, is day 4 workable?', want: 'airport' },
  { id: 'a09', text: 'Will we reach the station on time?', want: 'airport' },
  { id: 'a10', text: 'Our return flight is early morning', want: 'airport' },
  { id: 'a11', text: 'Do we need to skip anything to catch the flight?', want: 'airport' },
  { id: 'a12', text: 'Time check before our departure commitment', want: 'airport' },
  { id: 'a13', text: 'Can we add one more stop and still catch the train?', want: 'airport' },
  { id: 'a14', text: 'Departure day looks tight', want: 'airport' },
  { id: 'a15', text: 'We have a fixed flight time, will the plan work?', want: 'airport' },
  { id: 'a16', text: 'How early should we leave for the airport?', want: 'airport' },

  // ---- c: spend less overall (handler: cheaperAlternative) ----
  { id: 'c01', text: 'How do we cut the bill?', want: 'cheaper' },
  { id: 'c02', text: 'This is beyond our pocket, any way to spend less?', want: 'cheaper' },
  { id: 'c03', text: 'Reduce our fuel spend', want: 'cheaper' },
  { id: 'c04', text: 'Ways to bring the cost down', want: 'cheaper' },
  { id: 'c05', text: 'We are over budget, what can we trim?', want: 'cheaper' },
  { id: 'c06', text: 'How can we save money on this trip?', want: 'cheaper' },
  { id: 'c07', text: 'Can we do this cheaper?', want: 'cheaper' },
  { id: 'c08', text: 'Our budget is tight, suggest swaps', want: 'cheaper' },
  { id: 'c09', text: 'Where can we cut corners without ruining it?', want: 'cheaper' },
  { id: 'c10', text: 'Cheaper stays would help', want: 'cheaper' },
  { id: 'c11', text: 'Any way to reduce entry fees?', want: 'cheaper' },
  { id: 'c12', text: 'We want to spend less overall', want: 'cheaper' },
  { id: 'c13', text: 'Bring the per person cost down', want: 'cheaper' },
  { id: 'c14', text: 'Looking for a leaner version of this plan', want: 'cheaper' },
  { id: 'c15', text: 'Money is tight, what should we drop?', want: 'cheaper' },

  // ---- k: what does it cost (handler: costSummary) ----
  { id: 'k01', text: 'How much will this set us back in total?', want: 'cost' },
  { id: 'k02', text: 'Total damage?', want: 'cost' },
  { id: 'k03', text: 'What is this trip going to cost?', want: 'cost' },
  { id: 'k04', text: 'Show me the money split', want: 'cost' },
  { id: 'k05', text: 'What are we spending on fuel vs stay?', want: 'cost' },
  { id: 'k06', text: 'Per person cost please', want: 'cost' },
  { id: 'k07', text: 'Give me the cost breakdown', want: 'cost' },
  { id: 'k08', text: 'What is the daily spend?', want: 'cost' },
  { id: 'k09', text: 'How much per head?', want: 'cost' },
  { id: 'k10', text: 'Breakdown of expenses', want: 'cost' },
  { id: 'k11', text: 'What does this add up to?', want: 'cost' },
  { id: 'k12', text: 'Show the totals', want: 'cost' },

  // ---- r: wet weather (handler: rainPlan) ----
  { id: 'r01', text: 'What if it pours while we are in Munnar?', want: 'rain' },
  { id: 'r02', text: 'Need a monsoon backup plan', want: 'rain' },
  { id: 'r03', text: 'It might drizzle on day 3, plan B?', want: 'rain' },
  { id: 'r04', text: 'What are our options if it rains?', want: 'rain' },
  { id: 'r05', text: 'Wet weather plan', want: 'rain' },
  { id: 'r06', text: 'What do we do if the weather turns?', want: 'rain' },
  { id: 'r07', text: 'Backup for a washed out day', want: 'rain' },
  { id: 'r08', text: 'Rain is forecast, what changes?', want: 'rain' },
  { id: 'r09', text: 'Can we swap outdoor stops if it rains?', want: 'rain' },
  { id: 'r10', text: 'Monsoon contingency please', want: 'rain' },
  { id: 'r11', text: 'Give us an indoor alternative for day 2', want: 'rain' },
  { id: 'r12', text: 'What if the trek gets rained out?', want: 'rain' },
  { id: 'r13', text: 'Poor weather plan', want: 'rain' },
  { id: 'r14', text: 'Suggest a wet day itinerary', want: 'rain' },

  // ---- f: gentler for a family group (handler: familyVersion) ----
  { id: 'f01', text: 'We have a 6 year old, make it kid friendly', want: 'family' },
  { id: 'f02', text: 'Travelling with my in-laws, tone it down a notch', want: 'family' },
  { id: 'f03', text: 'Make it suitable for our family', want: 'family' },
  { id: 'f04', text: 'We are travelling with a baby', want: 'family' },
  { id: 'f05', text: 'Make this work for three generations', want: 'family' },
  { id: 'f06', text: 'Gentler version for the family', want: 'family' },
  { id: 'f07', text: 'We have grandparents along', want: 'family' },
  { id: 'f08', text: 'Family trip, please make it easier', want: 'family' },
  { id: 'f09', text: 'Adjust for travelling with young ones', want: 'family' },
  { id: 'f10', text: 'Make it a family trip pace', want: 'family' },
  { id: 'f11', text: 'We are four adults and two children', want: 'family' },
  { id: 'f12', text: 'Softer schedule for our group', want: 'family' },
  { id: 'f13', text: 'Family-friendly version please', want: 'family' },
  { id: 'f14', text: 'Make it easier for the older folks', want: 'family' },

  // ---- d: what to drop with children (handler: removeForKids) ----
  { id: 'd01', text: 'My toddler will get bored, what is too long?', want: 'kids' },
  { id: 'd02', text: 'Which stops are not good for kids?', want: 'kids' },
  { id: 'd03', text: 'What should we remove if we are travelling with children?', want: 'kids' },
  { id: 'd04', text: 'Anything unsuitable for a 4 year old?', want: 'kids' },
  { id: 'd05', text: 'Which activities are too much for children?', want: 'kids' },
  { id: 'd06', text: 'What will bore my kids?', want: 'kids' },
  { id: 'd07', text: 'Stops to skip with a small child', want: 'kids' },
  { id: 'd08', text: 'Which attractions are too long for kids?', want: 'kids' },
  { id: 'd09', text: 'What is not child friendly here?', want: 'kids' },
  { id: 'd10', text: 'Advise what to drop for the children', want: 'kids' },

  // ---- p: relaxed vs packed (handler: compareRelaxedPacked) ----
  { id: 'p01', text: 'Compare a relaxed itinerary with a packed itinerary', want: 'compare' },
  { id: 'p02', text: 'Compare day 1 and day 2', want: 'compare' },
  { id: 'p03', text: 'We want to relax but also pack a lot in', want: 'compare' },
  { id: 'p04', text: 'Relaxed vs packed, what suits us?', want: 'compare' },
  { id: 'p05', text: 'Should we do more or less per day?', want: 'compare' },
  { id: 'p06', text: 'Show a slower and a faster version', want: 'compare' },
  { id: 'p07', text: 'What is the difference between taking it easy and going all out?', want: 'compare' },
  { id: 'p08', text: 'Trade off between relaxed and packed', want: 'compare' },
  { id: 'p09', text: 'Lighter vs heavier plan', want: 'compare' },
  { id: 'p10', text: 'Do we see more with a packed schedule?', want: 'compare' },
  { id: 'p11', text: 'Compare the relaxed and packed options', want: 'compare' },
  { id: 'p12', text: 'Which is better, fewer stops or more?', want: 'compare' },

  // ---- s: what could go wrong (handler: biggestRisks) ----
  { id: 's01', text: 'What should we worry about in this plan?', want: 'risks' },
  { id: 's02', text: 'What could go wrong?', want: 'risks' },
  { id: 's03', text: 'Is this plan safe for a first-time hill driver?', want: 'risks' },
  { id: 's04', text: 'Where are the weak points?', want: 'risks' },
  { id: 's05', text: 'What are the danger areas?', want: 'risks' },
  { id: 's06', text: 'Any red flags in this itinerary?', want: 'risks' },
  { id: 's07', text: 'What is risky here?', want: 'risks' },
  { id: 's08', text: 'Where might we get stuck?', want: 'risks' },
  { id: 's09', text: 'What are the main problems with this plan?', want: 'risks' },
  { id: 's10', text: 'Anything I should be cautious about?', want: 'risks' },
  { id: 's11', text: 'Flag the trouble spots', want: 'risks' },
  { id: 's12', text: 'What are the biggest problems?', want: 'risks' },
  { id: 's13', text: 'Is this itinerary overambitious?', want: 'risks' },
  { id: 's14', text: 'Things that could derail this trip', want: 'risks' },

  // ---- y: delayed in transit (handler: delayBackup) ----
  { id: 'y01', text: 'What if we get stuck in traffic?', want: 'delay' },
  { id: 'y02', text: 'Backup if the cab breaks down', want: 'delay' },
  { id: 'y03', text: 'What if we are running late?', want: 'delay' },
  { id: 'y04', text: 'Contingency for a delay', want: 'delay' },
  { id: 'y05', text: 'What happens if we lose two hours?', want: 'delay' },
  { id: 'y06', text: 'Plan for a late start', want: 'delay' },
  { id: 'y07', text: 'Something goes wrong on the road, then what?', want: 'delay' },
  { id: 'y08', text: 'Fallback if a leg takes longer than planned', want: 'delay' },
  { id: 'y09', text: 'We are often late, what is the cushion?', want: 'delay' },
  { id: 'y10', text: 'Breakdown plan', want: 'delay' },
  { id: 'y11', text: 'Delay contingency please', want: 'delay' },
  { id: 'y12', text: 'What if the bus is late?', want: 'delay' },

  // ---- u: promotional copy (handler: youtubeDescription) ----
  { id: 'u01', text: 'Write a caption for my Instagram reel', want: 'youtube' },
  { id: 'u02', text: 'Draft a blog intro for this trip', want: 'youtube' },
  { id: 'u03', text: 'Turn this itinerary into a YouTube description', want: 'youtube' },
  { id: 'u04', text: 'Write a post for social media', want: 'youtube' },
  { id: 'u05', text: 'Give me a video description', want: 'youtube' },
  { id: 'u06', text: 'Caption ideas for my photos', want: 'youtube' },
  { id: 'u07', text: 'Write copy for the reel', want: 'youtube' },
  { id: 'u08', text: 'Promo text for this itinerary', want: 'youtube' },
  { id: 'u09', text: 'Make a description for my vlog', want: 'youtube' },
  { id: 'u10', text: 'Instagram caption for day 2', want: 'youtube' },
  { id: 'u11', text: 'Write something I can publish about this trip', want: 'youtube' },
  { id: 'u12', text: 'SEO description for this route', want: 'youtube' },

  // ---- m: recap the plan (handler: planSummary) ----
  { id: 'm01', text: 'Give me the high level version', want: 'summary' },
  { id: 'm02', text: 'Recap the whole plan please', want: 'summary' },
  { id: 'm03', text: 'Summarise this trip', want: 'summary' },
  { id: 'm04', text: 'What does the trip look like overall?', want: 'summary' },
  { id: 'm05', text: 'Give me the overview', want: 'summary' },
  { id: 'm06', text: 'Quick recap', want: 'summary' },
  { id: 'm07', text: 'Run me through the plan', want: 'summary' },
  { id: 'm08', text: 'What is the shape of this trip?', want: 'summary' },
  { id: 'm09', text: 'Brief me on the itinerary', want: 'summary' },
  { id: 'm10', text: 'High level summary', want: 'summary' },
  { id: 'm11', text: 'Tell me about this trip', want: 'summary' },
  { id: 'm12', text: 'Overview of the whole thing', want: 'summary' },

  // ---- n: outside the assistant's scope — the honest answer is "none" ----
  { id: 'n01', text: 'Should we take the train from Munnar to Thekkady?', want: 'none' },
  { id: 'n02', text: 'Is there a rainbow viewpoint nearby?', want: 'none' },
  { id: 'n03', text: 'Any budget hotels near Thekkady?', want: 'none' },
  { id: 'n04', text: 'My kid wants to see the aquarium, can we add it?', want: 'none' },
  { id: 'n05', text: 'Should we remove the fort or the museum?', want: 'none' },
  { id: 'n06', text: 'Our car is a hatchback with 5 people and luggage, will that work?', want: 'none' },
  { id: 'n07', text: 'Where is the best dosa in Kochi?', want: 'none' },
  { id: 'n08', text: 'Can you add a stop at Munnar?', want: 'none' },
  { id: 'n09', text: 'What is the weather tomorrow?', want: 'none' },
  { id: 'n10', text: 'Who voted for this stop?', want: 'none' },
  { id: 'n11', text: 'Sort my itinerary by cost', want: 'none' },
  { id: 'n12', text: 'Book a hotel for us', want: 'none' },
  { id: 'n13', text: 'Is Munnar better than Thekkady?', want: 'none' },
  { id: 'n14', text: 'Find me a homestay', want: 'none' },
  { id: 'n15', text: 'What is the road condition to Munnar?', want: 'none' },
  { id: 'n16', text: 'How many kilometres is this trip?', want: 'none' },
  { id: 'n17', text: 'Rename day 2 please', want: 'none' },
  { id: 'n18', text: 'Delete the museum stop', want: 'none' },
  { id: 'n19', text: 'Which restaurant should we eat at in Kochi?', want: 'none' },
  { id: 'n20', text: 'Add a rest day', want: 'none' },
  { id: 'n21', text: 'Is this itinerary public?', want: 'none' },
  { id: 'n22', text: 'Can you invite my friend to this trip?', want: 'none' },
  { id: 'n23', text: 'What is the fuel price today?', want: 'none' },
  { id: 'n24', text: 'Show me photos of Munnar', want: 'none' },
  { id: 'n25', text: 'Translate this into Malayalam', want: 'none' },

  // ---- x: traps — false-positive keywords and genuinely ambiguous asks ----
  { id: 'x01', text: 'How do we relax on this trip?', want: 'tiring' },
  { id: 'x02', text: 'Is day 3 too packed?', want: 'compare' },
  { id: 'x03', text: 'Can we afford the extra day?', want: 'cost' },
  { id: 'x04', text: 'Make it family friendly', want: 'family' },
  { id: 'x05', text: 'We only have till Sunday noon', want: 'none' },
  { id: 'x06', text: 'Is there a train option?', want: 'none' },
  { id: 'x07', text: 'It is raining in Munnar, what do we do?', want: 'rain' },
  { id: 'x08', text: 'Should we carry raincoats?', want: 'none' },
  { id: 'x09', text: 'The plan is packed and we are relaxed people', want: 'compare' },
  { id: 'x10', text: 'We want a budget friendly stay', want: 'cheaper' },
  { id: 'x11', text: 'How much time do we have before the flight?', want: 'airport' },
  { id: 'x12', text: 'What is the risk of rain on day 2?', want: 'rain' },
  { id: 'x13', text: 'Any cheaper family options?', want: 'cheaper' },
  { id: 'x14', text: 'Our child cannot handle long drives', want: 'family' },
  { id: 'x15', text: 'Is the museum open on Monday?', want: 'none' },
  { id: 'x16', text: 'Can we combine day 1 and day 2?', want: 'none' },
  { id: 'x17', text: 'Explain the health score', want: 'summary' },
  { id: 'x18', text: 'What is the cost per person per day?', want: 'cost' },
]
